import {
  Input,
  // FormItem,
  Space,
  Select,
  FormLayout,
  FormGrid,
  FormButtonGroup,
  Submit,
  Reset,
  DatePicker,
  TimePicker,
  InputNumber,
  Transfer,
  Cascader,
  Radio,
  Checkbox,
  Upload,
  Switch,
  ArrayCards,
  ArrayItems,
  ArrayTable,
  ArrayTabs,
  ArrayCollapse,
  FormCollapse,//折叠面板
  FormStep,
  FormTab,
  FormDialog,
  FormDrawer,
  Card,
  Editable,
  PreviewText,
  // TreeSelect,树选择
  // Rate,评分器
  // Slider,滚动条
  // PassWord,密码输入
} from "@formily/element-plus";

export const Plus = {
  Input,
  // FormItem,
  Space,
  Select,
  FormLayout,
  FormGrid,
  FormButtonGroup,
  Submit,
  Reset,
  DatePicker,
  TimePicker,
  InputNumber,
  Transfer,
  Cascader,
  Radio,
  Checkbox,
  Upload,
  Switch,
  ArrayCards,
  ArrayItems,
  ArrayTable,
  ArrayTabs,
  ArrayCollapse,
  FormCollapse,
  FormStep,
  FormTab,
  FormDialog,
  FormDrawer,
  Editable,
  PreviewText,
};
// export function useElement() {
//   return {
//     Input,
//     FormItem,
//     Space,
//     Select,
//     FormLayout,
//     FormGrid,
//     FormButtonGroup,
//     Submit,
//     Reset,
//     DatePicker,
//     TimePicker,
//     InputNumber,
//     Transfer,
//     Cascader,
//     Radio,
//     Checkbox,
//     Upload,
//     Switch,
//     ArrayCards,
//     ArrayItems,
//     ArrayTable,
//     ArrayTabs,
//     FormCollapse,
//     FormStep,
//     FormTab,
//     FormDialog,
//     FormDrawer,
//     Editable,
//     PreviewText,
//   };
// }
